### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by mart-e** [jdiez17/pastepm#2]
A README file or installations instructions would be nice. Reading the code I see I need flask, sqlalchemy and redis but what and how to deploy is harder.

Thanks

**Comment by jdiez17** [comment]
I will get to it as soon as I get access to a proper computer, I'm on a crappy netbook atm.

Basically, you'll need flask, sqlalchemy and redis, you need to create a 'config.ini' file following the 'config.sample.ini' layout and populate it with your details. To create the database, simply run the create-database script.

**Comment by adduc** [comment]
There's also a dependency on paypal

**Comment by jdiez17** [comment]
Only if you want to use the PayPal functionality, which is not finished
yet.

**Comment by jdiez17** [comment]
OK, I have added the documentation. Feel free to reopen an issue or submit a pull request if you don't think it's enough.

Thanks!
